module "message_queue" {
  source              = "git::https://github.com/tothenew/terraform-aws-queue.git?ref=v0.0.2"
  create_aws_activemq     = false
  create_aws_ec2_rabbitmq = true
  vpc_id  = data.aws_vpc.selected.id
  ec2_subnet_id =  data.aws_subnets.private.ids[0]
  subnet_ids = data.aws_subnets.private.ids  
  common_tags = local.tags
  worker  = 0
  master  = 1
  key_name = local.workspace["key_name"]
  kms_key_id = "arn:aws:kms:eu-central-1:454578700264:key/a5174342-81ec-4788-9b45-1f49280c4bd4"
  instance_type = local.workspace["queue"]["instance_type"]
  disable_api_termination = true
  disable_api_stop        = false
  root_volume_size = 50
  vpc_cidr_block = data.aws_vpc.selected.cidr_block
  environment_name = local.workspace.environment_name
  region = local.workspace["aws"]["region"]
  project_name_prefix = "TTN"
}
